### ISSUE TITLE
Error with 男女  - 

### ISSUE THREAD

**Issue by MadisKarli** [timmahrt/pyJuliusAlign#4]
Hi, thanks for the great tool!

I'm having some issues with the following input:
男女 - romajiList = ['d a N j y o']

The model in Julius Segmentation Kit does not understand j-y in triphone (no issues with monophone):

> Error: voca_load_htkdict: line 1: triphone "N-j+y" not found
Error: voca_load_htkdict: line 1: triphone "j-y+o" not found
Error: voca_load_htkdict: the line content was: 0 [w_0] d a N j y o
Error: voca_load_htkdict: begin missing phones
Error: voca_load_htkdict: N-j+y
Error: voca_load_htkdict: j-y+o
Error: voca_load_htkdict: the line content was: 0 [w_0] d a N j y o

j y is already in cabocha-0.69(posset = IPA) output: 男女;男女;ダンジョ;d a N j y o

This all means that alignment fails with:

> ERROR: Error in loading model
Traceback (most recent call last):
  File "align_example.py", line 54, in <module>
    alignFromTextgrid.forceAlignCorpus(wavPath=path,
  File "/home/username/.local/lib/python3.8/site-packages/pyjuliusalign/alignFromTextgrid.py", line 201, in forceAlignCorpus
    output = forceAlignFile([name, ], wavPath, wavNameDict, txtPath,
  File "/home/username/.local/lib/python3.8/site-packages/pyjuliusalign/alignFromTextgrid.py", line 155, in forceAlignFile
    output = juliusAlignment.juliusAlignCabocha(dataDict[speaker], wavPath,
  File "/home/username/.local/lib/python3.8/site-packages/pyjuliusalign/juliusAlignment.py", line 210, in juliusAlignCabocha
    adjustedPhonList[-1][1] = intervalEnd
IndexError: list index out of range

Any idea if this comes from pyJuliusAlign or if the issue is with cabocha or with the model used in Julius Segmentation Kit?

**Comment by timmahrt** [comment]
Hello,
Unfortunately, I'm not really sure.  I should be able to look into it this weekend though.

Tim

**Comment by timmahrt** [comment]
Thanks for the heads up.  That was a nasty bug.  I had never tested the code with a triphone model and yeah, it was completely broken.

If you're interested to know there were 3 or 4 separate bugs but the root cause was that 1) I was not properly segmenting phones into syllables that I fed julius.  This was resolved by sending kana to julius and letting julius do the segmentation itself 2) I use cabocha for breaking phrases into words and phones but cabocha's phones are different from julius.  So I wrote a mapping between the two in order to group the segmented phones produced by julius into the words determined by cabocha.

The solution is a little fuzzy and I can't guarantee it won't break in some situations.  I did test your case using 男女 and triphone models.  It worked ok!

I've made a new release.  It requires a new dependency:
`python -m pip install python-Levenshtein`

If you encounter any problems, please let me know.

I'm sorry for the hassle.
Tim

**Comment by MadisKarli** [comment]
Thanks for the quick response and fix!
